version: "3.3"
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_DATABASE
    ports:
      - "5432:5432"
    volumes:
      - library_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  library_data: {}
